I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 493, in script
    show message_yuli_background zoom 2 at right
Exception: Image 'message_yuli_background' does not accept attributes 'zoom 2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 493, in script
    show message_yuli_background zoom 2 at right
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "C:\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "C:\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "C:\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'message_yuli_background' does not accept attributes 'zoom 2'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
TechTales 1.0
Sun Mar 12 01:59:39 2023
