I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 420, in script call
    call kfc_minigame
  File "game/script.rpy", line 420, in script call
    call kfc_minigame
ScriptError: could not find label 'kfc_minigame'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 420, in script call
    call kfc_minigame
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1705, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 420, in script call
    call kfc_minigame
  File "C:\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'kfc_minigame'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
TechTales 1.0
Mon Mar 13 01:51:11 2023
